name: 'Nx get affected apps action'
description: '"Determines the affected apps in an Nx workspace'
inputs:
  base:
    description: 'SHA to compare from'
    default: 'origin/main'
    required: false
  head:
    description: 'SHA to compare to'
    default: 'origin/main~1'
    required: false
  exclude:
    description: 'List of applications that need to be excluded'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
