name: 'Nx get affected apps action'
description: '"Determines the affected apps in an Nx workspace'
inputs:
  base:
    description: 'SHA to compare from'
    default: 'origin/main'
    required: false
  head:
    description: 'SHA to compare to'
    default: 'origin/main~1'
    required: false
  registry:
    description: 'Docker registry where the image belongs to'
    default: 'gcr.io/ingka-dsm-portal-dev'
    required: false
  version:
    description: 'Version of the Docker image'
    default: 'v1.0.0'
    required: false
outputs:
  affected_apps:
    description: 'an array of affected app names'
runs:
  using: 'node12'
  main: 'dist/index.js'
